In [12]:
#coding: utf-8
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import sys, os
import cv2
from PIL import Image

In [9]:
def image_resize(im):
    height = 100
    width = 100
    resize_img = cv2.resize(im, (width, height))
    
    return resize_img

In [35]:
import sys, os
in_jpg = "out_asumi/"
out_jpg = "resize_asumi/"
#リストで結果を返す関数
def get_file(dir_path):
    filenames = os.listdir(dir_path)
    return filenames
 
pic = get_file(in_jpg)
print(pic[0])

out_000235.jpg_no1


In [44]:
in_jpg = "out_iguchi/"
out_jpg = "resize_iguchi/"
pic = get_file(in_jpg)
for i in range(len(pic)):
    img = cv2.imread(in_jpg + pic[i])
    #print(img)
    #resize_img =img.resize((100, 100))
    resize_img = cv2.resize(img, (100, 100))
    #print(resize_img)
    save_path = out_jpg + 'out_{}.jpg'.format(i+1)
    print(save_path)
    cv2.imwrite(save_path, resize_img)

resize_iguchi/out_1.jpg
resize_iguchi/out_2.jpg
resize_iguchi/out_3.jpg
resize_iguchi/out_4.jpg
resize_iguchi/out_5.jpg
resize_iguchi/out_6.jpg
resize_iguchi/out_7.jpg
resize_iguchi/out_8.jpg
resize_iguchi/out_9.jpg
resize_iguchi/out_10.jpg
resize_iguchi/out_11.jpg
resize_iguchi/out_12.jpg
resize_iguchi/out_13.jpg
resize_iguchi/out_14.jpg
resize_iguchi/out_15.jpg
resize_iguchi/out_16.jpg
resize_iguchi/out_17.jpg
resize_iguchi/out_18.jpg
resize_iguchi/out_19.jpg
resize_iguchi/out_20.jpg
resize_iguchi/out_21.jpg
resize_iguchi/out_22.jpg
resize_iguchi/out_23.jpg
resize_iguchi/out_24.jpg
resize_iguchi/out_25.jpg
resize_iguchi/out_26.jpg
resize_iguchi/out_27.jpg
resize_iguchi/out_28.jpg
resize_iguchi/out_29.jpg
resize_iguchi/out_30.jpg
resize_iguchi/out_31.jpg
resize_iguchi/out_32.jpg
resize_iguchi/out_33.jpg
resize_iguchi/out_34.jpg
resize_iguchi/out_35.jpg
resize_iguchi/out_36.jpg
resize_iguchi/out_37.jpg
resize_iguchi/out_38.jpg
resize_iguchi/out_39.jpg
resize_iguchi/out_40.jpg
resize_ig

In [40]:
img = cv2.imread(in_jpg + pic[0])
#print(img)
#resize_img =img.resize((100, 100))
resize_img = cv2.resize(img, (100, 100))
print(resize_img)
save_path = out_jpg + 'out_{}.jpg'.format(1)
print(save_path)
cv2.imwrite(save_path, resize_img)

[[[239 230 220]
  [238 230 221]
  [238 231 222]
  ...
  [ 14  21  36]
  [ 16  23  38]
  [ 19  26  41]]

 [[238 229 219]
  [238 230 220]
  [237 230 221]
  ...
  [ 16  22  39]
  [ 19  26  41]
  [ 22  29  44]]

 [[238 229 219]
  [237 229 219]
  [235 229 220]
  ...
  [ 17  25  41]
  [ 22  29  45]
  [ 26  34  49]]

 ...

 [[105 103 102]
  [100  98  97]
  [112 110 109]
  ...
  [179 188 226]
  [180 188 226]
  [180 188 226]]

 [[151 149 148]
  [117 115 114]
  [ 97  95  94]
  ...
  [177 186 224]
  [177 186 224]
  [177 186 224]]

 [[188 186 185]
  [135 133 132]
  [ 93  90  89]
  ...
  [175 184 222]
  [175 184 222]
  [175 184 222]]]
resize_asumi/out_1.jpg


True